#!/bin/bash

# copied from https://github.com/mkropat/sh-realpath.git
function abs_path {
    canonicalize_path "$(resolve_symlinks "$1")"
}

resolve_symlinks() {
    _resolve_symlinks "$1"
}

_resolve_symlinks() {
    _assert_no_path_cycles "$@" || return

    local dir_context path
    path=$(readlink -- "$1")
    if [ $? -eq 0 ]; then
        dir_context=$(dirname -- "$1")
        _resolve_symlinks "$(_prepend_dir_context_if_necessary "$dir_context" "$path")" "$@"
    else
        printf '%s\n' "$1"
    fi
}

_prepend_dir_context_if_necessary() {
    if [ "$1" = . ]; then
        printf '%s\n' "$2"
    else
        _prepend_path_if_relative "$1" "$2"
    fi
}

_prepend_path_if_relative() {
    case "$2" in
        /* ) printf '%s\n' "$2" ;;
         * ) printf '%s\n' "$1/$2" ;;
    esac
}

_assert_no_path_cycles() {
    local target path

    target=$1
    shift

    for path in "$@"; do
        if [ "$path" = "$target" ]; then
            return 1
        fi
    done
}

canonicalize_path() {
    if [ -d "$1" ]; then
        _canonicalize_dir_path "$1"
    else
        _canonicalize_file_path "$1"
    fi
}

_canonicalize_dir_path() {
    (cd "$1" 2>/dev/null && pwd -P)
}

_canonicalize_file_path() {
    local dir file
    dir=$(dirname -- "$1")
    file=$(basename -- "$1")
    (cd "$dir" 2>/dev/null && printf '%s/%s\n' "$(pwd -P)" "$file")
}

# if ! [ "${DYNDOC_DOCKER_HOME}" ] && [ -f "${HOME}/.dyndoc_docker_home" ]; then
# 		DYNDOC_DOCKER_HOME="`cat ${HOME}/.dyndoc_docker_home`"
# fi

ddyn() {
if [ "${DYNDOC_DOCKER_HOME}" ]; then
		if ! [ "${DYNDOC_DOCKER_LIBRARY}" ]; then
			DYNDOC_DOCKER_LIBRARY="${DYNDOC_DOCKER_HOME}/library"
		fi
		if ! [ "${DYNDOC_DOCKER_PROJECT}" ]; then
			DYNDOC_DOCKER_PROJECT="${DYNDOC_DOCKER_HOME}/proj"
		fi
else
	echo "Environment variable DYNDOC_DOCKER_HOME is unset"
	exit
fi

## docker run -v requires absolute path!
if [ "${DYNDOC_DOCKER_LIBRARY}" ]; then
	DYNDOC_DOCKER_LIBRARY=`abs_path "${DYNDOC_DOCKER_LIBRARY}"`
else	 
	echo "Environment variable DYNDOC_DOCKER_LIBRARY is unset"
	exit
fi
if [ "${DYNDOC_DOCKER_PROJECT}" ]; then	
	DYNDOC_DOCKER_PROJECT=`abs_path "${DYNDOC_DOCKER_PROJECT}"`
else	 
	echo "Environment variable DYNDOC_DOCKER_PROJECT is unset"
	exit
fi

cmd="$1"
shift
case "$cmd" in
env)
	echo "DYNDOC_DOCKER_HOME=$DYNDOC_DOCKER_HOME"
	echo "DYNDOC_DOCKER_LIBRARY=$DYNDOC_DOCKER_LIBRARY"
	echo "DYNDOC_DOCKER_PROJECT=$DYNDOC_DOCKER_PROJECT"
;;
start | restart | stop)
	if [ "$cmd" = "stop" ] || [ "$cmd" = "restart" ]; then
		docker stop dyndoc &>/dev/null; docker rm dyndoc &>/dev/null
	fi
	if [ "$cmd" = "start" ] || [ "$cmd" = "restart" ]; then
		docker run -d \
		-p 7777:7777 \
		-v ${DYNDOC_DOCKER_PROJECT}:/dyndoc-proj \
		-v ${DYNDOC_DOCKER_LIBRARY}:/dyndoc-library \
		--name dyndoc \
		dyndoc &>/dev/null
	fi
	echo "docker dyndoc: $cmd server!"
;;
R | irb  | gem) 
	docker exec -ti dyndoc $cmd $*
;;
bash)
	docker exec -ti dyndoc /bin/bash
;;
prj)
	cmd2="$1"
	projname="$2"
	projroot="${DYNDOC_DOCKER_PROJECT}/${projname}"
	etcproj="${DYNDOC_DOCKER_HOME}/etc/proj"
	case "$cmd2" in
	model)
		model="$2"
		if [ -e "${etcproj}/model_${model}.sh" ]; then
			echo "$2" > ${etcproj}/default.model
			echo "default model is now ${model}"
		else
			echo "Warning: $2 is not a proper model"
		fi
	;;
	*)
		# The 2 following lines ensures that actions are loaded!
		model="`cat ${etcproj}/default.model`"
		. ${etcproj}/model_${model}.sh
		shift;shift
		##echo "model_action ${cmd2} ${projname} $*"
		model_action ${cmd2} ${projname} $*
	;;
	esac
;;
set | get) #shortcut of "ddyn prj cd|set <proj>"
	###DEBUG: echo "_ddyn_prj $cmd $*"
	_ddyn_prj $cmd $* 
;;
cd )
	proj="$1"
	path=""
	if [[ $proj =~ (.*):(.*) ]]; then 
		proj=${BASH_REMATCH[1]}
		path=${BASH_REMATCH[2]}
	fi
	### DEBUG: echo "<proj=$proj and path=$path >"
	_ddyn_prj set $proj
	if [ "$(_ddyn_prj name)" = "$proj" ]; then
		goto="$(_ddyn_prj root)/$path"
		if [ -d "$goto" ]; then
			cd $goto
		else
			echo "$goto is not a valid directory!"
		fi
	fi 
;;
add)
	ddyn prj $(_ddyn_prj name) $*
;;
*)
	last="${@: -1}"
	length=$(($#-1))
	all_but_last="${@:1:$length}"
	filename=`abs_path ${last}`
	filename2=${filename/${DYNDOC_DOCKER_PROJECT}//dyndoc-proj}
	if [ "$filename" = "$filename2" ]; then
		echo "dyndoc file to compile not in the project root!"
		exit
	fi
	docker exec dyndoc dyn $all_but_last $filename2
;;
esac
}

_ddyn_prj() {
	case "$1" in
	set)
		projname="$2"
		projroot="${DYNDOC_DOCKER_PROJECT}/${projname}"
		if [ -d $projroot ]; then 
			export current_projname="${projname}"
			export current_projroot="${projroot}"
		else
			echo "$projname is not a valid project name!"
		fi
	;;
	name) echo "$current_projname";;
	root) echo "$current_projroot";;
	esac
}
