#!/bin/bash

# copied from https://github.com/mkropat/sh-realpath.git
function abs_path {
    canonicalize_path "$(resolve_symlinks "$1")"
}

resolve_symlinks() {
    _resolve_symlinks "$1"
}

_resolve_symlinks() {
    _assert_no_path_cycles "$@" || return

    local dir_context path
    path=$(readlink -- "$1")
    if [ $? -eq 0 ]; then
        dir_context=$(dirname -- "$1")
        _resolve_symlinks "$(_prepend_dir_context_if_necessary "$dir_context" "$path")" "$@"
    else
        printf '%s\n' "$1"
    fi
}

_prepend_dir_context_if_necessary() {
    if [ "$1" = . ]; then
        printf '%s\n' "$2"
    else
        _prepend_path_if_relative "$1" "$2"
    fi
}

_prepend_path_if_relative() {
    case "$2" in
        /* ) printf '%s\n' "$2" ;;
         * ) printf '%s\n' "$1/$2" ;;
    esac
}

_assert_no_path_cycles() {
    local target path

    target=$1
    shift

    for path in "$@"; do
        if [ "$path" = "$target" ]; then
            return 1
        fi
    done
}

canonicalize_path() {
    if [ -d "$1" ]; then
        _canonicalize_dir_path "$1"
    else
        _canonicalize_file_path "$1"
    fi
}

_canonicalize_dir_path() {
    (cd "$1" 2>/dev/null && pwd -P)
}

_canonicalize_file_path() {
    local dir file
    dir=$(dirname -- "$1")
    file=$(basename -- "$1")
    (cd "$dir" 2>/dev/null && printf '%s/%s\n' "$(pwd -P)" "$file")
}

# # Not used!
# function item_in_list {
#   local list="$2"
#   local item="$1"
#   if [[ $list =~ (^|[[:space:]])"$item"($|[[:space:]]) ]] ; then
#     # yes, list include item
#     result="${item}"
#   else
#     result=""
#   fi
#   return $result
# }

# if ! [ "${DYNDOC_DOCKER_HOME}" ] && [ -f "${HOME}/.dyndoc_docker_home" ]; then
# 		DYNDOC_DOCKER_HOME="`cat ${HOME}/.dyndoc_docker_home`"
# fi

ddyn() {
if [ "${DYNDOC_DOCKER_HOME}" ]; then
		if ! [ "${DYNDOC_DOCKER_LIBRARY}" ]; then
			DYNDOC_DOCKER_LIBRARY="${DYNDOC_DOCKER_HOME}/library"
		fi
		if ! [ "${DYNDOC_DOCKER_PROJECT}" ]; then
			DYNDOC_DOCKER_PROJECT="${DYNDOC_DOCKER_HOME}/proj"
		fi
else
	echo "Environment variable DYNDOC_DOCKER_HOME is unset"
	exit
fi

## docker run -v requires absolute path!
if [ "${DYNDOC_DOCKER_LIBRARY}" ]; then
	DYNDOC_DOCKER_LIBRARY=`abs_path "${DYNDOC_DOCKER_LIBRARY}"`
else	 
	echo "Environment variable DYNDOC_DOCKER_LIBRARY is unset"
	exit
fi
if [ "${DYNDOC_DOCKER_PROJECT}" ]; then	
	DYNDOC_DOCKER_PROJECT=`abs_path "${DYNDOC_DOCKER_PROJECT}"`
else	 
	echo "Environment variable DYNDOC_DOCKER_PROJECT is unset"
	exit
fi

cmd="$1"
case "$cmd" in
env)
	echo "DYNDOC_DOCKER_HOME=$DYNDOC_DOCKER_HOME"
	echo "DYNDOC_DOCKER_LIBRARY=$DYNDOC_DOCKER_LIBRARY"
	echo "DYNDOC_DOCKER_PROJECT=$DYNDOC_DOCKER_PROJECT"
;;
start | restart | stop)
	if [ "$cmd" = "stop" ] || [ "$cmd" = "restart" ]; then
		docker stop dyndoc &>/dev/null; docker rm dyndoc &>/dev/null
	fi
	if [ "$cmd" = "start" ] || [ "$cmd" = "restart" ]; then
		docker run -d \
		-p 7777:7777 \
		-v ${DYNDOC_DOCKER_PROJECT}:/dyndoc-proj \
		-v ${DYNDOC_DOCKER_LIBRARY}:/dyndoc-library \
		--name dyndoc \
		dyndoc &>/dev/null
	fi
	echo "docker dyndoc: $cmd server!"
;;
R | irb  | gem) 
	shift
	docker exec -ti dyndoc $cmd $*
;;
bash)
	docker exec -ti dyndoc /bin/bash
;;
prj)
	shift
	cmd2="$1"
	projname="$2"
	projroot="${DYNDOC_DOCKER_PROJECT}/${projname}"
	etcproj="${DYNDOC_DOCKER_HOME}/etc/proj"
	case "$cmd2" in
	model)
		model="$2"
		if [ -e "${etcproj}/model_${model}.sh" ]; then
			echo "$2" > ${etcproj}/default.model
			echo "default model is now ${model}"
		else
			echo "Warning: $2 is not a proper model"
		fi
	;;
	ls)
		echo `ls ${DYNDOC_DOCKER_PROJECT}`
	;;
	*)
		# The 2 following lines ensures that actions are loaded!
		model="`cat ${etcproj}/default.model`"
		. ${etcproj}/model_${model}.sh
		shift;shift
		##echo "model_action ${cmd2} ${projname} $*"
		model_action ${cmd2} ${projname} $*
	;;
	esac
;;
set | name | root) #shortcut of "ddyn prj cd|set <proj>"
	###DEBUG: echo "_ddyn_prj $cmd $*"
	shift
	_ddyn_prj $cmd $* 
;;
cd )
	shift
	proj="$1"
	_ddyn_prj path "$proj"
	if [ -d $DYNDOC_DOCKER_LAST_PROJECT_PATH ]; then
		cd $DYNDOC_DOCKER_LAST_PROJECT_PATH
	else
		echo "$DYNDOC_DOCKER_LAST_PROJECT_PATH is not a valid directory!"
	fi 
;;
*)
	last="${@: -1}"
	length=$(($#-1))
	dyn_options="${@:1:$length}" #all but last
	##echo "<$last> <$dyn_options>"
	filename=`abs_path ${last}`
	filename2=${filename/${DYNDOC_DOCKER_PROJECT}//dyndoc-proj}
	if [ "$filename" = "$filename2" ]; then
		_ddyn_in_room ${filename} $dyn_options
	else
		docker exec dyndoc dyn $dyn_options $filename2
	fi
;;
esac
}

## to compile a dyndoc file not in the project folder!
_ddyn_in_room() {
	filename="$1"
	dyn_options="$2"
	dname=`dirname $filename`
	bname=`basename $filename`
	#no extension for bname and dname at the end with / replaced by - 
	projroot="${DYNDOC_DOCKER_PROJECT}/rooms/${bname%%.*}${dname//\//-}" 
	projname="${projroot}/${bname}"
	# clean room directory if existing and not empty 
	if [ -d ${projroot} ]; then rm -fr ${projroot}/*; fi

	echo "temporary room ${projroot} created!"
	mkdir -p ${projroot}
	cd $dname
	cp -r * ${projroot}
	echo "current files copied in temporary room ${projroot}!"
	projname2=${projname/${DYNDOC_DOCKER_PROJECT}//dyndoc-proj}
	echo "$projname2 to compile"
	docker exec dyndoc dyn $dyn_options $projname2
	cd $dname
	cp -r ${projroot}/* .
	echo "current files copied from temporary room ${projroot}!"
}

_ddyn_prj() {
	case "$1" in
	set)
		projname="$2"
		projroot="${DYNDOC_DOCKER_PROJECT}/${projname}"
		if [ -d $projroot ]; then 
			export DYNDOC_DOCKER_CURRENT_PROJECT_NAME="${projname}"
			export DYNDOC_DOCKER_CURRENT_PROJECT_ROOT="${projroot}"
		else
			echo "$projname is not a valid project name!"
		fi
	;;
	name) echo "$DYNDOC_DOCKER_CURRENT_PROJECT_NAME";;
	root) echo "$DYNDOC_DOCKER_CURRENT_PROJECT_ROOT";;
	path) #detect the project and path
		projname="$2";pathname="" #this is the default (only projname provided)
		if [[ $projname =~ (.*):(.*) ]]; then 
			projname=${BASH_REMATCH[1]}
			pathname=${BASH_REMATCH[2]}
		else if [[ $projname =~ / ]]; then 
			pathname=$projname
			if [ "$DYNDOC_DOCKER_CURRENT_PROJECT_NAME" ]; then
				projname=$DYNDOC_DOCKER_CURRENT_PROJECT_NAME
			else
				echo "current project unset (see 'ddyn set')"
				exit
			fi
		fi
		if ! [ "$pathname" = "/*" ]; then pathname="/$pathname"; fi
		projroot="$DYNDOC_DOCKER_PROJECT/$projname"
		export DYNDOC_DOCKER_LAST_PROJECT_NAME="${projname}"
		export DYNDOC_DOCKER_LAST_PROJECT_ROOT="${projroot}"
		if ! [ -d $DYNDOC_DOCKER_LAST_PROJECT_ROOT ]; then
			echo "$DYNDOC_DOCKER_LAST_PROJECT_NAME is not a valid project name!"
			exit
		fi
		export DYNDOC_DOCKER_LAST_PROJECT_PATH="${projroot}${pathname}"
	fi
	;;
	esac
}
